# Generated by Django 3.1.1 on 2020-09-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='xxx',
        ),
    ]
