# Generated by Django 3.1.1 on 2020-09-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0003_auto_20200904_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Birth of Date'),
        ),
    ]
