# Generated by Django 3.1.1 on 2020-09-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0004_auto_20200904_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
